---
new_page_extension: md
auto_deploy: true
admin_path: 
webhook_url: 
sections:
- path: content
  label: Pages
  create: all
- path: content/contact
  label: Contact
  create: all
- path: content/implement
  label: Implement
  create: all
- path: content/learn
  label: Learn
  create: all
- path: content/about
  label: About
  create: all
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
version: '0.44'
